# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180912_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='g',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stu', to='app.Grade'),
        ),
        migrations.AddField(
            model_name='student',
            name='c',
            field=models.ManyToManyField(null=True, to='app.Course'),
        ),
    ]
